srun: /usr/lib64/slurm/select_alps.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/alps: Incompatible plugin version
srun: /usr/lib64/slurm/select_cray.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/cray: Incompatible plugin version
srun: /usr/lib64/slurm/select_serial.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/serial: Incompatible plugin version
srun: /usr/lib64/slurm/switch_cray.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for switch/cray: Incompatible plugin version
2023-10-29 14:12:43.967978: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
INFO flwr 2023-10-29 14:12:49,759 | grpc.py:49 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-10-29 14:12:49,762 | connection.py:42 | ChannelConnectivity.IDLE
DEBUG flwr 2023-10-29 14:12:49,762 | connection.py:42 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-10-29 14:12:49,763 | connection.py:42 | ChannelConnectivity.READY
DEBUG flwr 2023-10-29 14:12:49,971 | connection.py:139 | gRPC channel closed
Traceback (most recent call last):
  File "client_7.py", line 49, in <module>
    main()
  File "client_7.py", line 44, in main
    fl.client.start_numpy_client(server_address="10.30.0.254:9000",
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 288, in start_numpy_client
    start_client(
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 205, in start_client
    task_res, sleep_duration, keep_going = handle(client, task_ins)
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 82, in handle
    client_msg, sleep_duration, keep_going = handle_legacy_message(client, server_msg)
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 117, in handle_legacy_message
    return _get_parameters(client, server_msg.get_parameters_ins), 0, True
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 163, in _get_parameters
    get_parameters_res = maybe_call_get_parameters(
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/client.py", line 197, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 320, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
  File "/home/s124m21/projekat_DDU/client.py", line 105, in get_parameters
    if FED_BN:
NameError: name 'FED_BN' is not defined
srun: error: n03: task 0: Exited with exit code 1
